export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const STREAML_REQUEST = "STREAML_REQUEST";
export const STREAML_SUCCESS = "STREAML_SUCCESS";
export const STREAML_FAIL = "STREAML_FAIL";

export const SUBJECT_REQUEST = "SUBJECT_REQUEST";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
export const SUBJECT_FAIL = "SUBJECT_FAIL";
