export const GET_ALL_STUDENT_REQUEST = "GET_ALL_STUDENT_REQUEST";
export const GET_ALL_STUDENT_REQUEST_SUCCESS =
  "GET_ALL_STUDENT_REQUEST_SUCCESS";
export const GET_ALL_STUDENT_REQUEST_FAIL = "GET_ALL_STUDENT_REQUEST_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_FAIL = "REGISTER_REQUEST_FAIL";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
